#!/bin/sh

# Show wifi 📶 and percent strength or 📡 if none.
# Show 🌐 if connected to ethernet or ❎ if none.

case $BLOCK_BUTTON in
	1) $TERMINAL -e nmtui ;;
	3) notify-send "🌐 Internet module" "\- Click to connect
📡: no wifi connection
📶: wifi connection with quality
❎: no ethernet
🌐: ethernet working
" ;;
esac

grep "down" /sys/class/net/w*/operstate &>/dev/null && wifiicon="wifi:--" ||
	wifiicon="$(grep "^\s*w" /proc/net/wireless | awk '{ printf "wifi: %d%", int($3 * 100 / 70) }')"
# grep "up" /syclass/net/e*/operstate &>/dev/null && wiredicon=" wired" ||
# 	wiredicon=""

printf "%s" "$wifiicon"

