#!/bin/sh

datediff() {
    d1=$(date -d "$1" +%s)
    d2=$(date -d "$2" +%s)
    echo $(( (d1 - d2) / (86400 * 24) )) hours
}

find "${XDG_CONFIG_HOME:-$HOME/.config}"/work_profiles -name 'lock' | while read line; do
	profile="$(dirname "$line")"
	start=$(sed '2q;d' "$line")
	end=$(date +%s)
	working_time=$(echo "($end-$start) / 60 / 60" | bc -l)

	printf "%s: %.2fh\n" "${profile##*/}" "$working_time"
done
